export enum Statistic {
  // Quick Look
  'SkillRating' = 'SkillRating',
  'TDMSkillRating' = 'TDMSkillRating',
  'CTFSkillRating' = 'CTFSkillRating',
  'DMSkillRating' = 'DMSkillRating',
  'ShowdownSkillRating' = 'ShowdownSkillRating',
  'MatchesPlayed' = 'MatchesPlayed',
  'MatchesQuit' = 'MatchesQuit',
  'TimePlayed' = 'TimePlayed',
  'Wins' = 'Wins',
  'Losses' = 'Losses',
  'Kills' = 'Kills',
  'Deaths' = 'Deaths',
  'Suicides' = 'Suicides',

  // Kill Achievements
  'MultiKillLevel0' = 'MultiKillLevel0',
  'MultiKillLevel1' = 'MultiKillLevel1',
  'MultiKillLevel2' = 'MultiKillLevel2',
  'MultiKillLevel3' = 'MultiKillLevel3',
  'SpreeKillLevel0' = 'SpreeKillLevel0',
  'SpreeKillLevel1' = 'SpreeKillLevel1',
  'SpreeKillLevel2' = 'SpreeKillLevel2',
  'SpreeKillLevel3' = 'SpreeKillLevel3',
  'SpreeKillLevel4' = 'SpreeKillLevel4',
  'BestShockCombo' = 'BestShockCombo',
  'AmazingCombos' = 'AmazingCombos',
  'AirRox' = 'AirRox',
  'FlakShreds' = 'FlakShreds',
  'AirSnot' = 'AirSnot',

  //Power Up Achievements
  'UDamageTime' = 'UDamageTime',
  'BerserkTime' = 'BerserkTime',
  'InvisibilityTime' = 'InvisibilityTime',
  'UDamageCount' = 'UDamageCount',
  'BerserkCount' = 'BerserkCount',
  'InvisibilityCount' = 'InvisibilityCount',
  'BootJumps' = 'BootJumps',
  'ShieldBeltCount' = 'ShieldBeltCount',
  'ArmorVestCount' = 'ArmorVestCount',
  'ArmorPadsCount' = 'ArmorPadsCount',
  'HelmetCount' = 'HelmetCount',
  'KegCount' = 'KegCount',

  //Weapons
  'Accuracy' = 'Accuracy',
  'ImpactHammerKills' = 'ImpactHammerKills',
  'ImpactHammerDeaths' = 'ImpactHammerDeaths',

  'EnforcerKills' = 'EnforcerKills',
  'EnforcerDeaths' = 'EnforcerDeaths',
  'EnforcerShots' = 'EnforcerShots',
  'EnforcerHits' = 'EnforcerHits',

  'BioRifleKills' = 'BioRifleKills',
  'BioRifleDeaths' = 'BioRifleDeaths',
  'BioRifleShots' = 'BioRifleShots',
  'BioRifleHits' = 'BioRifleHits',

  'BioLauncherKills' = 'BioLauncherKills',
  'BioLauncherDeaths' = 'BioLauncherDeaths',
  'BioLauncherShots' = 'BioLauncherShots',
  'BioLauncherHits' = 'BioLauncherHits',

  'ShockBeamKills' = 'ShockBeamKills',
  'ShockBeamDeaths' = 'ShockBeamDeaths',
  'ShockCoreKills' = 'ShockCoreKills',
  'ShockCoreDeaths' = 'ShockCoreDeaths',
  'ShockComboKills' = 'ShockComboKills',
  'ShockComboDeaths' = 'ShockComboDeaths',
  'ShockRifleShots' = 'ShockRifleShots',
  'ShockRifleHits' = 'ShockRifleHits',

  'LinkKills' = 'LinkKills',
  'LinkDeaths' = 'LinkDeaths',
  'LinkBeamKills' = 'LinkBeamKills',
  'LinkBeamDeaths' = 'LinkBeamDeaths',
  'LinkShots' = 'LinkShots',
  'LinkHits' = 'LinkHits',

  'MinigunKills' = 'MinigunKills',
  'MinigunDeaths' = 'MinigunDeaths',
  'MinigunShardKills' = 'MinigunShardKills',
  'MinigunShardDeaths' = 'MinigunShardDeaths',
  'MinigunShots' = 'MinigunShots',
  'MinigunHits' = 'MinigunHits',

  'FlakShardKills' = 'FlakShardKills',
  'FlakShardDeaths' = 'FlakShardDeaths',
  'FlakShellKills' = 'FlakShellKills',
  'FlakShellDeaths' = 'FlakShellDeaths',
  'FlakShots' = 'FlakShots',
  'FlakHits' = 'FlakHits',

  'RocketKills' = 'RocketKills',
  'RocketDeaths' = 'RocketDeaths',
  'RocketShots' = 'RocketShots',
  'RocketHits' = 'RocketHits',

  'SniperKills' = 'SniperKills',
  'SniperDeaths' = 'SniperDeaths',
  'SniperHeadshotKills' = 'SniperHeadshotKills',
  'SniperHeadshotDeaths' = 'SniperHeadshotDeaths',
  'SniperShots' = 'SniperShots',
  'SniperHits' = 'SniperHits',

  'LightningRiflePrimaryKills' = 'LightningRiflePrimaryKills',
  'LightningRiflePrimaryDeaths' = 'LightningRiflePrimaryDeaths',
  'LightningRifleSecondaryKills' = 'LightningRifleSecondaryKills',
  'LightningRifleSecondaryDeaths' = 'LightningRifleSecondaryDeaths',
  'LightningRifleShots' = 'LightningRifleShots',
  'LightningRifleHits' = 'LightningRifleHits',

  'RedeemerKills' = 'RedeemerKills',
  'RedeemerDeaths' = 'RedeemerDeaths',
  'RedeemerShots' = 'RedeemerShots',
  'RedeemerHits' = 'RedeemerHits',

  'InstagibKills' = 'InstagibKills',
  'InstagibDeaths' = 'InstagibDeaths',
  'InstagibShots' = 'InstagibShots',
  'InstagibHits' = 'InstagibHits',

  'TelefragKills' = 'TelefragKills',
  'TelefragDeaths' = 'TelefragDeaths',

  // Movement
  'RunDist' = 'RunDist',
  'SprintDist' = 'SprintDist',
  'InAirDist' = 'InAirDist',
  'SwimDist' = 'SwimDist',
  'TranslocDist' = 'TranslocDist',
  'NumDodges' = 'NumDodges',
  'NumWallDodges' = 'NumWallDodges',
  'NumJumps' = 'NumJumps',
  'NumLiftJumps' = 'NumLiftJumps',
  'NumFloorSlides' = 'NumFloorSlides',
  'NumWallRuns' = 'NumWallRuns',
  'NumImpactJumps' = 'NumImpactJumps',
  'NumRocketJumps' = 'NumRocketJumps',
  'SlideDist' = 'SlideDist',
  'WallRunDist' = 'WallRunDist',

  // CTF
  'FlagCaptures' = 'FlagCaptures',
  'FlagReturns' = 'FlagReturns',
  'FlagAssists' = 'FlagAssists',
  'FlagHeldDeny' = 'FlagHeldDeny',
  'FlagHeldDenyTime' = 'FlagHeldDenyTime',
  'FlagHeldTime' = 'FlagHeldTime',
  'FlagReturnPoints' = 'FlagReturnPoints',
  'CarryAssist' = 'CarryAssist',
  'CarryAssistPoints' = 'CarryAssistPoints',
  'FlagCapPoints' = 'FlagCapPoints',
  'DefendAssist' = 'DefendAssist',
  'DefendAssistPoints' = 'DefendAssistPoints',
  'ReturnAssist' = 'ReturnAssist',
  'ReturnAssistPoints' = 'ReturnAssistPoints',
  'TeamCapPoints' = 'TeamCapPoints',
  'EnemyFCDamage' = 'EnemyFCDamage',
  'FCKills' = 'FCKills',
  'FCKillPoints' = 'FCKillPoints',
  'FlagSupportKills' = 'FlagSupportKills',
  'FlagSupportKillPoints' = 'FlagSupportKillPoints',
  'RegularKillPoints' = 'RegularKillPoints',
  'FlagGrabs' = 'FlagGrabs',
  'AttackerScore' = 'AttackerScore',
  'DefenderScore' = 'DefenderScore',
  'SupporterScore' = 'SupporterScore',
  'TeamKills' = 'TeamKills'
}
