export enum Statistic {
    // Quick Look
    "SkillRating" = "Duel MMR",
    "TDMSkillRating" = "TDM MMR",
    "CTFSkillRating" = "CTF MMR",
    "DMSkillRating" = "DM MMR",
    "ShowdownSkillRating" = "Showdown MMR",
    "FlagRunSkillRating" = "FlagRunSkillRating",
    "RankedDuelSkillRating" = "RankedDuelSkillRating",
    "RankedCTFSkillRating" = "RankedCTFSkillRating",
    "RankedShowdownSkillRating" = "RankedShowdownSkillRating",
    "RankedFlagRunSkillRating" = "RankedFlagRunSkillRating",
    "MatchesPlayed" = "MatchesPlayed",
    "MatchesQuit" = "MatchesQuit",
    "TimePlayed" = "TimePlayed",
    "Wins" = "Wins",
    "Losses" = "Losses",
    "Kills" = "Kills",
    "Deaths" = "Deaths",
    "Suicides" = "Suicides",

    // Kill Achievements
    "MultiKillLevel0" = "Double Kills",
    "MultiKillLevel1" = "Multi Kills",
    "MultiKillLevel2" = "Ultra Kills",
    "MultiKillLevel3" = "Monster Kills",
    "SpreeKillLevel0" = "Killing Sprees",
    "SpreeKillLevel1" = "Rampages",
    "SpreeKillLevel2" = "Dominatings",
    "SpreeKillLevel3" = "Unstoppables",
    "SpreeKillLevel4" = "Godlikes",
    "BestShockCombo" = "Best Shock Combo",
    "AmazingCombos" = "Amazing Combos",
    "AirRox" = "Air Rox",
    "FlakShreds" = "Flak Shreds",
    "AirSnot" = "Air Snot",

    //Power Up Achievements
    "UDamageTime" = "UDamage Time",
    "BerserkTime" = "Berserk Time",
    "InvisibilityTime" = "Invisibility Time",
    "UDamageCount" = "UDamage Count",
    "BerserkCount" = "Berserk Count",
    "InvisibilityCount" = "Invisibility Count",
    "BootJumps" = "Boot Jumps",
    "ShieldBeltCount" = "Shield Belt Count",
    "ArmorVestCount" = "Armor Vest Count",
    "ArmorPadsCount" = "Armor Pads Count",
    "HelmetCount" = "Helmet Count",
    "KegCount" = "Keg Count",

    //Weapons
    "Accuracy" = "Accuracy",
    "ImpactHammerKills" = "Kills",
    "ImpactHammerDeaths" = "Deaths",

    "EnforcerKills" = "Kills",
    "EnforcerDeaths" = "Deaths",
    "EnforcerShots" = "Shots",
    "EnforcerHits" = "Hits",

    "BioRifleKills" = "Kills",
    "BioRifleDeaths" = "Deaths",
    "BioRifleShots" = "Shots",
    "BioRifleHits" = "Hits",

    "BioLauncherKills" = "Kills",
    "BioLauncherDeaths" = "Deaths",
    "BioLauncherShots" = "Shots",
    "BioLauncherHits" = "Hits",

    "ShockBeamKills" = "Beam Kills",
    "ShockBeamDeaths" = "Beam Deaths",
    "ShockCoreKills" = "Core Kills",
    "ShockCoreDeaths" = "Core Deaths",
    "ShockComboKills" = "Combo Kills",
    "ShockComboDeaths" = "Combo Deaths",
    "ShockRifleShots" = "Shots",
    "ShockRifleHits" = "Hits",

    "LinkKills" = "Kills",
    "LinkDeaths" = "Deaths",
    "LinkBeamKills" = "Beam Kills",
    "LinkBeamDeaths" = "Beam Deaths",
    "LinkShots" = "Shots",
    "LinkHits" = "Hits",

    "MinigunKills" = "Kills",
    "MinigunDeaths" = "Deaths",
    "MinigunShardKills" = "Shard Kills",
    "MinigunShardDeaths" = "Shard Deaths",
    "MinigunShots" = "Shots",
    "MinigunHits" = "Hits",

    "FlakShardKills" = "Shard Kills",
    "FlakShardDeaths" = "Shard Deaths",
    "FlakShellKills" = "Shell Kills",
    "FlakShellDeaths" = "Shell Deaths",
    "FlakShots" = "Shots",
    "FlakHits" = "Hits",

    "RocketKills" = "Kills",
    "RocketDeaths" = "Deaths",
    "RocketShots" = "Shots",
    "RocketHits" = "Hits",

    "SniperKills" = "Kills",
    "SniperDeaths" = "Deaths",
    "SniperHeadshotKills" = "Headshot Kills",
    "SniperHeadshotDeaths" = "Headshot Deaths",
    "SniperShots" = "Shots",
    "SniperHits" = "Hits",

    "LightningRiflePrimaryKills" = "Primary Kills",
    "LightningRiflePrimaryDeaths" = "Primary Deaths",
    "LightningRifleSecondaryKills" = "Secondary Kills",
    "LightningRifleSecondaryDeaths" = "Secondary Deaths",
    "LightningRifleShots" = "Shots",
    "LightningRifleHits" = "Hits",

    "RedeemerKills" = "Kills",
    "RedeemerDeaths" = "Deaths",
    "RedeemerShots" = "Shots",
    "RedeemerHits" = "Hits",
    
    "InstagibKills" = "Kills",
    "InstagibDeaths" = "Deaths",
    "InstagibShots" = "Shots",
    "InstagibHits" = "Hits",

    "TelefragKills" = "Kills",
    "TelefragDeaths" = "Deaths",

    // Movement
    "RunDist" = "Run Distance",
    "SprintDist" = "Sprint Distance",
    "InAirDist" = "In Air Distance",
    "SwimDist" = "Swim Distance",
    "TranslocDist" = "Translocator Distance",
    "NumDodges" = "Dodges",
    "NumWallDodges" = "Wall Dodges",
    "NumJumps" = "Jumps",
    "NumLiftJumps" = "Lift Jumps",
    "NumFloorSlides" = "Floor Slides",
    "NumWallRuns" = "Wall Runs",
    "NumImpactJumps" = "Impact Jumps",
    "NumRocketJumps" = "Rocket Jumps",
    "SlideDist" = "Slide Dist",
    "WallRunDist" = "Wall Run Dist",

    // CTF
    "FlagCaptures" = "Flag Captures",
    "FlagReturns" = "Flag Returns",
    "FlagAssists" = "Flag Assists",
    "FlagHeldDeny" = "Flag Held Deny",
    "FlagHeldDenyTime" = "Flag Held Deny Time",
    "FlagHeldTime" = "Flag Held Time",
    "FlagReturnPoints" = "Flag Return Points",
    "CarryAssist" = "Carry Assist",
    "CarryAssistPoints" = "Carry Assist Points",
    "FlagCapPoints" = "Flag Cap Points",
    "DefendAssist" = "Defend Assist",
    "DefendAssistPoints" = "Defend Assist Points",
    "ReturnAssist" = "Return Assist",
    "ReturnAssistPoints" = "Return Assist Points",
    "TeamCapPoints" = "Team Cap Points",
    "EnemyFCDamage" = "Enemy FC Damage",
    "FCKills" = "FC Kills",
    "FCKillPoints" = "FC Kill Points",
    "FlagSupportKills" = "Flag Support Kills",
    "FlagSupportKillPoints" = "Flag Support Kill Points",
    "RegularKillPoints" = "Regular Kill Points",
    "FlagGrabs" = "Flag Grabs",
    "AttackerScore" = "Attacker Score",
    "DefenderScore" = "Defender Score",
    "SupporterScore" = "Supporter Score",
    "TeamKills" = "Team Kills"
}