import { Statistic } from './statistic';

export const StatisticDisplay: Record<Statistic, string> = {
	// Quick Look
	[Statistic.SkillRating]: 'Duel MMR',
	[Statistic.TDMSkillRating]: 'TDM MMR',
	[Statistic.CTFSkillRating]: 'CTF MMR',
	[Statistic.DMSkillRating]: 'DM MMR',
	[Statistic.ShowdownSkillRating]: 'Showdown MMR',
	[Statistic.MatchesPlayed]: 'Matches Played',
	[Statistic.MatchesQuit]: 'Matches Quit',
	[Statistic.TimePlayed]: 'Time Played',
	[Statistic.Wins]: 'Wins',
	[Statistic.Losses]: 'Losses',
	[Statistic.Kills]: 'Kills',
	[Statistic.Deaths]: 'Deaths',
	[Statistic.Suicides]: 'Suicides',

	// Kill Achievements
	[Statistic.MultiKillLevel0]: 'Double Kills',
	[Statistic.MultiKillLevel1]: 'Multi Kills',
	[Statistic.MultiKillLevel2]: 'Ultra Kills',
	[Statistic.MultiKillLevel3]: 'Monster Kills',
	[Statistic.SpreeKillLevel0]: 'Killing Sprees',
	[Statistic.SpreeKillLevel1]: 'Rampages',
	[Statistic.SpreeKillLevel2]: 'Dominatings',
	[Statistic.SpreeKillLevel3]: 'Unstoppables',
	[Statistic.SpreeKillLevel4]: 'Godlikes',
	[Statistic.BestShockCombo]: 'Best Shock Combo',
	[Statistic.AmazingCombos]: 'Amazing Combos',
	[Statistic.AirRox]: 'Air Rox',
	[Statistic.FlakShreds]: 'Flak Shreds',
	[Statistic.AirSnot]: 'Air Snot',

	//Power Up Achievements
	[Statistic.UDamageTime]: 'UDamage Time',
	[Statistic.BerserkTime]: 'Berserk Time',
	[Statistic.InvisibilityTime]: 'Invisibility Time',
	[Statistic.UDamageCount]: 'UDamage Count',
	[Statistic.BerserkCount]: 'Berserk Count',
	[Statistic.InvisibilityCount]: 'Invisibility Count',
	[Statistic.BootJumps]: 'Boot Jumps',
	[Statistic.ShieldBeltCount]: 'Shield Belt Count',
	[Statistic.ArmorVestCount]: 'Armor Vest Count',
	[Statistic.ArmorPadsCount]: 'Armor Pads Count',
	[Statistic.HelmetCount]: 'Helmet Count',
	[Statistic.KegCount]: 'Keg Count',

	//Weapons
	[Statistic.Accuracy]: 'Accuracy',
	[Statistic.ImpactHammerKills]: 'Kills',
	[Statistic.ImpactHammerDeaths]: 'Deaths',

	[Statistic.EnforcerKills]: 'Kills',
	[Statistic.EnforcerDeaths]: 'Deaths',
	[Statistic.EnforcerShots]: 'Shots',
	[Statistic.EnforcerHits]: 'Hits',

	[Statistic.BioRifleKills]: 'Kills',
	[Statistic.BioRifleDeaths]: 'Deaths',
	[Statistic.BioRifleShots]: 'Shots',
	[Statistic.BioRifleHits]: 'Hits',

	[Statistic.BioLauncherKills]: 'Kills',
	[Statistic.BioLauncherDeaths]: 'Deaths',
	[Statistic.BioLauncherShots]: 'Shots',
	[Statistic.BioLauncherHits]: 'Hits',

	[Statistic.ShockBeamKills]: 'Beam Kills',
	[Statistic.ShockBeamDeaths]: 'Beam Deaths',
	[Statistic.ShockCoreKills]: 'Core Kills',
	[Statistic.ShockCoreDeaths]: 'Core Deaths',
	[Statistic.ShockComboKills]: 'Combo Kills',
	[Statistic.ShockComboDeaths]: 'Combo Deaths',
	[Statistic.ShockRifleShots]: 'Shots',
	[Statistic.ShockRifleHits]: 'Hits',

	[Statistic.LinkKills]: 'Kills',
	[Statistic.LinkDeaths]: 'Deaths',
	[Statistic.LinkBeamKills]: 'Beam Kills',
	[Statistic.LinkBeamDeaths]: 'Beam Deaths',
	[Statistic.LinkShots]: 'Shots',
	[Statistic.LinkHits]: 'Hits',

	[Statistic.MinigunKills]: 'Kills',
	[Statistic.MinigunDeaths]: 'Deaths',
	[Statistic.MinigunShardKills]: 'Shard Kills',
	[Statistic.MinigunShardDeaths]: 'Shard Deaths',
	[Statistic.MinigunShots]: 'Shots',
	[Statistic.MinigunHits]: 'Hits',

	[Statistic.FlakShardKills]: 'Shard Kills',
	[Statistic.FlakShardDeaths]: 'Shard Deaths',
	[Statistic.FlakShellKills]: 'Shell Kills',
	[Statistic.FlakShellDeaths]: 'Shell Deaths',
	[Statistic.FlakShots]: 'Shots',
	[Statistic.FlakHits]: 'Hits',

	[Statistic.RocketKills]: 'Kills',
	[Statistic.RocketDeaths]: 'Deaths',
	[Statistic.RocketShots]: 'Shots',
	[Statistic.RocketHits]: 'Hits',

	[Statistic.SniperKills]: 'Kills',
	[Statistic.SniperDeaths]: 'Deaths',
	[Statistic.SniperHeadshotKills]: 'Headshot Kills',
	[Statistic.SniperHeadshotDeaths]: 'Headshot Deaths',
	[Statistic.SniperShots]: 'Shots',
	[Statistic.SniperHits]: 'Hits',

	[Statistic.LightningRiflePrimaryKills]: 'Primary Kills',
	[Statistic.LightningRiflePrimaryDeaths]: 'Primary Deaths',
	[Statistic.LightningRifleSecondaryKills]: 'Secondary Kills',
	[Statistic.LightningRifleSecondaryDeaths]: 'Secondary Deaths',
	[Statistic.LightningRifleShots]: 'Shots',
	[Statistic.LightningRifleHits]: 'Hits',

	[Statistic.RedeemerKills]: 'Kills',
	[Statistic.RedeemerDeaths]: 'Deaths',
	[Statistic.RedeemerShots]: 'Shots',
	[Statistic.RedeemerHits]: 'Hits',

	[Statistic.InstagibKills]: 'Kills',
	[Statistic.InstagibDeaths]: 'Deaths',
	[Statistic.InstagibShots]: 'Shots',
	[Statistic.InstagibHits]: 'Hits',

	[Statistic.TelefragKills]: 'Kills',
	[Statistic.TelefragDeaths]: 'Deaths',

	// Movement
	[Statistic.RunDist]: 'Run Distance',
	[Statistic.SprintDist]: 'Sprint Distance',
	[Statistic.InAirDist]: 'In Air Distance',
	[Statistic.SwimDist]: 'Swim Distance',
	[Statistic.TranslocDist]: 'Translocator Distance',
	[Statistic.NumDodges]: 'Dodges',
	[Statistic.NumWallDodges]: 'Wall Dodges',
	[Statistic.NumJumps]: 'Jumps',
	[Statistic.NumLiftJumps]: 'Lift Jumps',
	[Statistic.NumFloorSlides]: 'Floor Slides',
	[Statistic.NumWallRuns]: 'Wall Runs',
	[Statistic.NumImpactJumps]: 'Impact Jumps',
	[Statistic.NumRocketJumps]: 'Rocket Jumps',
	[Statistic.SlideDist]: 'Slide Dist',
	[Statistic.WallRunDist]: 'Wall Run Dist',

	// CTF
	[Statistic.FlagCaptures]: 'Flag Captures',
	[Statistic.FlagReturns]: 'Flag Returns',
	[Statistic.FlagAssists]: 'Flag Assists',
	[Statistic.FlagHeldDeny]: 'Flag Held Deny',
	[Statistic.FlagHeldDenyTime]: 'Flag Held Deny Time',
	[Statistic.FlagHeldTime]: 'Flag Held Time',
	[Statistic.FlagReturnPoints]: 'Flag Return Points',
	[Statistic.CarryAssist]: 'Carry Assist',
	[Statistic.CarryAssistPoints]: 'Carry Assist Points',
	[Statistic.FlagCapPoints]: 'Flag Cap Points',
	[Statistic.DefendAssist]: 'Defend Assist',
	[Statistic.DefendAssistPoints]: 'Defend Assist Points',
	[Statistic.ReturnAssist]: 'Return Assist',
	[Statistic.ReturnAssistPoints]: 'Return Assist Points',
	[Statistic.TeamCapPoints]: 'Team Cap Points',
	[Statistic.EnemyFCDamage]: 'Enemy FC Damage',
	[Statistic.FCKills]: 'FC Kills',
	[Statistic.FCKillPoints]: 'FC Kill Points',
	[Statistic.FlagSupportKills]: 'Flag Support Kills',
	[Statistic.FlagSupportKillPoints]: 'Flag Support Kill Points',
	[Statistic.RegularKillPoints]: 'Regular Kill Points',
	[Statistic.FlagGrabs]: 'Flag Grabs',
	[Statistic.AttackerScore]: 'Attacker Score',
	[Statistic.DefenderScore]: 'Defender Score',
	[Statistic.SupporterScore]: 'Supporter Score',
	[Statistic.TeamKills]: 'Team Kills'
};
