export enum ServerAttribute {
  hubGuid = 'UT_HUBGUID_s',
  serverInstanceGuid = 'UT_SERVERINSTANCEGUID_s',
  serverName = 'UT_SERVERNAME_s',
  serverMotd = 'UT_SERVERMOTD_s',
  playersOnline = 'UT_PLAYERONLINE_i',
  spectatorsOnline = 'UT_SPECTATORSONLINE_i',
  maxPlayers = 'UT_MAXPLAYERS_i',
  gameMode = 'GAMEMODE_s',
  gameType = 'GAMENAME_s',
  mapName = 'MAPNAME_s',
  matchState = 'UT_MATCHSTATE_s',
  matchDuration = 'UT_MATCHDURATION_i',
  serverTrustLevel = 'UT_SERVERTRUSTLEVEL_i',
  gameInstance = 'UT_GAMEINSTANCE_i',
  serverVersion = 'UT_SERVERVERSION_s',
  ranked = 'UT_RANKED_i',
  dcid = 'DCID_s',
  needs = 'NEEDS_i',
  playlist = 'PLAYLISTID_i',
  region = 'REGION_s',
  eloRangeStart = 'TEAMELO_i',
  eloRangeEnd = 'TEAMELO2_i'
}
